### ISSUE TITLE
Issue regarding the labels

### ISSUE THREAD

**Issue by JDBLab** [gdagstn/borges#1]
Hello,

I am getting the following error when I tried tun the PrepAtlas()-

labels` must have the same length as the number of points

I have added label as a character vector 2 ways but still not working. Could you please help?
progenitor1 <- DiabetesST2UMAP.combined$CellType %in% c(rep("A2.1", 100),
                                                        rep("D1", 100),
                                                        rep("A5", 100),
                                                        rep("D3", 100),
                                                        rep("A4", 100),
                                                        rep("A2", 100),
                                                        rep("D6", 100),
                                                        rep("A7", 100),
                                                        rep("A1", 100),
                                                        rep("S", 100),
                                                        rep("D2", 100),
                                                        rep("M", 100),           
                                                        rep("DX", 100),
                                                        rep("I", 100),
                                                        rep("D4", 100),
                                                        rep("E", 100),
                                                        rep("D7", 100))

OR

progenitor1 <- c(rep("A2.1"),
                                                        rep("D1"),
                                                        rep("A5"),
                                                        rep("D3"),
                                                        rep("A4"),
                                                        rep("A2"),
                                                        rep("D6"),
                                                        rep("A7"),
                                                        rep("A1"),
                                                        rep("S"),
                                                        rep("D2"),
                                                        rep("M"),           
                                                        rep("DX"),
                                                        rep("I"),
                                                        rep("D4"),
                                                        rep("E"),
                                                        rep("D7"))

**Comment by gdagstn** [comment]
Hi @JDBLab,

Thanks for reaching out. 

Would you mind making sure that `length(progenitor1)` is equal to `nrow(x)`, where x is the matrix or data.frame with the two columns? 

If you mock up an example you can check that your version of `borges` is working correctly:

```{r}
set.seed(123)

# 3 random 2D Gaussians, 100 points each
mats = rbind(matrix(rnorm(200, 1, 1), ncol = 2), 
                      matrix(rnorm(200, 3, 1), ncol = 2),
                      matrix(rnorm(200, 6, 1), ncol = 2))

# 3 labels
labels = c(rep("A", 100), rep("B", 100), rep("C", 100))

# prepare the atlas
atlas = prepAtlas(mats, res = 30, labels = labels)

# plot the atlas
plotAtlas(atlas)
```

![image](https://user-images.githubusercontent.com/21171362/221416783-a205a5a5-5d17-488c-ba55-270cd46d2322.png)


If instead I had a shorter label vector:

```{r}
labels = c(rep("A", 50), rep("B", 100), rep("C", 100))

# prepare the atlas
atlas = prepAtlas(mats, res = 30, labels = labels)

Error in prepAtlas(mats, res = 30, labels = labels) : 
  `labels` must have the same length as the number of points
```

Let me know if this example works for you.

**Comment by JDBLab** [comment]
Thank you @gdagstn for your prompt reply. I followed your instructions and attached the following results-
> length(progenitor1)
[1] 115825
> nrow(plotting.data)
[1] 115825
> 

Moreover,I have attached x= plottingd.data which is my data frame head shot for your information. I am not sure why I am getting error then

                           UMAP_1        UMAP_2
ctrl1st2_AAACCCAAGAAATCCA-1  6.795607e+00 -1.538425e+00
ctrl1st2_AAACCCAAGAGCCTGA-1 -1.006505e+01  3.285499e-01
ctrl1st2_AAACCCAAGTGGAAAG-1  5.728968e+00 -2.871461e+00
ctrl1st2_AAACCCAAGTGGTGAC-1  3.437918e+00  5.515788e+00
ctrl1st2_AAACCCACAAGGCGTA-1  4.841263e+00  1.525540e-01
ctrl1st2_AAACCCACACCCTTAC-1  7.806969e+00 -3.936992e+00
ctrl1st2_AAACCCACACCGTGAC-1  5.405604e+00  2.686605e+00
ctrl1st2_AAACCCACACGCTTAA-1 -9.723472e+00  6.568252e-01
ctrl1st2_AAACCCACACGTAGTT-1 -9.609337e+00 -6.842556e-01
ctrl1st2_AAACCCACACTGATTG-1  6.513480e+00 -1.580456e+00
ctrl1st2_AAACCCACACTGTTCC-1  4.997651e+00 -5.243851e+00
ctrl1st2_AAACCCACAGGCATGA-1  8.544131e+00 -3.920350e+00
ctrl1st2_AAACCCACATAACGGG-1  6.255911e+00 -2.801072e+00

**Comment by gdagstn** [comment]
I looked at the code that is supposed to check for length to generate that error, and I noticed a wrong check in the condition, but I don't think this is what generates an issue; in any case you can re-install the package now. 

It's not easy diagnosing the issue without the data you are using as input, but looking at the code from your first post, I think I may know what the error may be. 

Creating your `progenitor1` object this way:

```
progenitor1 <- DiabetesST2UMAP.combined$CellType %in% c(rep("A2.1", 100),
rep("D1", 100),
rep("A5", 100),
rep("D3", 100),
rep("A4", 100),
rep("A2", 100),
rep("D6", 100),
rep("A7", 100),
rep("A1", 100),
rep("S", 100),
rep("D2", 100),
rep("M", 100),
rep("DX", 100),
rep("I", 100),
rep("D4", 100),
rep("E", 100),
rep("D7", 100))
```

gives you a vector with values either TRUE or FALSE, since you are checking whether each element in `DiabetesST2UMAP.combined$CellType` can be found within the set of labels "A2.1", "D1", etc. 

Could you check the `class()` of the `progenitor1` object as well? If it's a vector of TRUE/FALSE values then it won't work as a label vector, since the function checks that you are giving a vector of class `character` or `factor` whereas `class(progenitor1)` is most likely a `logical`. 

If you are trying to subset the `DiabetesST2UMAP.combined$CellType` column according to which of these cell types are within your classification, you should do something like this:

```
labs = c("A2.1", "D1", "A5", "D3", "A4", "A2", "D6", "A7", "A1", "S", "D2", "M", "DX", "I", "D4", "E", "D7")
keep = which(DiabetesST2UMAP.combined$CellType %in% labs
progenitor1 = DiabetesST2UMAP.combined$CellType[keep]
```

And, at the same time (assuming the row order is the same for `DiabetesST2UMAP.combined` and `plotting.data`), you may need to do:

```
plotting.data = plotting.data[keep,]
```

And then run `prepAtlas()` again. 

As I said at the beginning, without looking at the original data it's hard to see what's wrong, but you can try these steps and let me know if they worked.

**Comment by gdagstn** [comment]
I am going to close it for now, but feel free to reopen if the issue persists.
